# Generated by Django 3.0.8 on 2020-09-04 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan', models.CharField(max_length=50)),
                ('shomare', models.CharField(max_length=50)),
                ('dore', models.IntegerField(default=1)),
                ('verified', models.IntegerField(default=0)),
                ('shenasname', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.get_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('students', models.ManyToManyField(to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan', models.CharField(max_length=50)),
                ('shomare', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('goone', models.CharField(choices=[('D', 'دبیرستان (متوسطه دوره دوم)'), ('R', 'راهنمایی (متوسطه دوره اول)'), ('S', 'مرکز سمپاد')], max_length=1)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OJHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(max_length=250)),
                ('handle', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
    ]
