# Generated by Django 2.2.12 on 2020-06-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200609_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dore',
            field=models.IntegerField(default=1),
        ),
    ]
