# Generated by Django 3.0.8 on 2020-09-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0002_student_supporter_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='supporter_tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
