# Generated by Django 3.0.8 on 2020-09-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200906_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='supporter_tags',
        ),
    ]
