# Generated by Django 2.2.12 on 2020-06-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_dore'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shomare',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
