# Generated by Django 2.2.12 on 2020-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='title',
            field=models.CharField(default='x', max_length=250),
            preserve_default=False,
        ),
    ]
