# Generated by Django 3.0.8 on 2020-09-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supportertag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportertag',
            name='user',
        ),
        migrations.AddField(
            model_name='supportertag',
            name='student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
