# Generated by Django 3.0.8 on 2020-09-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200906_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
