# Generated by Django 3.0.8 on 2020-08-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200815_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(max_length=250)),
                ('handle', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
    ]
