# Generated by Django 2.2.12 on 2020-06-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='x', max_length=250),
            preserve_default=False,
        ),
    ]
