# Generated by Django 3.0.8 on 2020-09-04 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='drop_off_date',
            field=models.DateField(default=datetime.date(2030, 1, 1)),
        ),
    ]
