# Generated by Django 3.0.8 on 2020-09-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson_drop_off_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='drop_off_date',
            field=models.DateField(),
        ),
    ]
