# Generated by Django 3.0.8 on 2020-08-15 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200613_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='release',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
