# Generated by Django 3.0.8 on 2020-09-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200906_0943'),
        ('main', '0001_initial'),
        ('course', '0004_auto_20200906_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
