# Generated by Django 3.0.8 on 2020-09-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
