# Generated by Django 3.0.8 on 2020-08-06 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200805_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
