# Generated by Django 3.0.8 on 2020-09-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('quiz', '0002_quiz_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qtag', to='main.Tag')),
            ],
        ),
    ]
