# Generated by Django 3.0.8 on 2020-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
