# Generated by Django 3.0.8 on 2020-09-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_collection_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='picture_url',
            field=models.URLField(default='https://cdn.quera.ir/overview/course-images/3-small.0-e8df0727a65f.jpg'),
        ),
    ]
