# Generated by Django 3.0.8 on 2020-08-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_studentgroup'),
        ('quiz', '0005_collection_collectionquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.StudentGroup'),
        ),
    ]
