# Generated by Django 3.0.8 on 2020-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_collection_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='expectedScore',
            field=models.IntegerField(default=0),
        ),
    ]
