# Generated by Django 3.0.8 on 2020-09-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_expectedscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='expectedScore',
        ),
        migrations.AddField(
            model_name='collectionquiz',
            name='expectedScore',
            field=models.IntegerField(default=0),
        ),
    ]
