# Generated by Django 3.0.8 on 2020-09-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200901_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('startValue', models.IntegerField()),
                ('endValue', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('labelColor', models.CharField(max_length=50)),
            ],
        ),
    ]
