# Generated by Django 3.0.8 on 2020-09-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
